plan:
    package: ./simpleApp
name: main
inputs:
    inputs.deploymentInputs.netlifyAccount.token:
        secret: ENC[AES256_GCM,data:zcRfSC9oI4RkkC94o7co/IlqqspigyrNjRPuHexJu/Kys6hMuNvs/fView==,iv:g+r9xLeVh/blodANGRvWk15meC4Ysp+NVrBAAkEm5tY=,tag:GiJitZ6jfkCgZpK/DpzMRw==,type:str]
    inputs.gitAuthToken:
        secret: ENC[AES256_GCM,data:1nptmr8O8aoKb76E2/+L7uUmQpvsitdzBaa403KmkK6iGnlAfrGbiQ==,iv:nyvIQS9jVlYALHR7dyoUcGc206vhgysru/6ELXL9ikU=,tag:UkP7gTzk9Psn0g0nk0YuOQ==,type:str]
    multistageDeployment.refs.email:
        text: guillaume.derouville@gmail.com
    multistageDeployment.refs.name:
        text: grouville
    multistageDeployment.refs.repository.source:
        dir:
            path: ./simpleApp/gitRepo
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1gxwmtwahzwdmrskhf90ppwlnze30lgpm056kuesrxzeuyclrwvpsupwtpk
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBodUhKbUlqWGtDQVk5ZytF
            WE14VEppcmU0SUVhZ2Nnc2Q2bXh5VWNvT1hvCldSdnpZMEJsQXgrK3F6L2R5R2lm
            dHBvMVFTUkFKY2R1Rld3ZmJ3UGMxbm8KLS0tIEVHSDAxbWtmbXVTUk02Qmt5T2Zq
            akI1a2ZOUzFTUXg5S01BZm9wd3dkWk0KYCJi1kySc7UhHdwVB5KXDiyBQTFzG0mh
            lIP6DEIG8SBqkBnrIQrugwo/BlzD/CB5XzB5XEViGZdUEdnOr9vCCg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2021-09-27T13:09:45Z"
    mac: ENC[AES256_GCM,data:RQoPrR073kO2e2qqnLfSicO4liFjsZacDBM4U1E/ij7NLAedaARS4Z6TFmA1NrcbVcjFpMMrwIjCTAi1E9wglgWhuI7mPcADc28+t3qEPD75bFadq7PbCA4VjeslgOATD3/Wr41XJT8Nqo/ZMlvdxmyPSdADiOd36nqbYfdKnfs=,iv:SVGdASeuQc9Pon6JZct7qJZ8MANVIuFCpczBL2ibDi4=,tag:ZmbpRDt9hhYIdX4UzyiFHQ==,type:str]
    pgp: []
    encrypted_suffix: secret
    version: 3.7.1
